### ISSUE TITLE
random Prowl_Ebooks post when you type !prowl

### ISSUE THREAD

**Issue by TheWadapan** [tf-wiki-discord/wikisearch#2]
perhaps just a normal twitter embed would do; the hard part is getting one randomly that works without continual maintenance

**Comment by TheWadapan** [comment]
would probably use the same code to work for Ask_Triton as well lmao

**Comment by tf-wiki-discord** [comment]
Twitter's got an API that lets you pull some tweets from it. It looks slightly annoying to setup, but that's probably the best way to do it: pull some tweets and randomly select one.

**Comment by tf-wiki-discord** [comment]
Leaving this here for later
https://developer.twitter.com/en/docs/labs/tweets-and-users/quick-start/get-tweets

**Comment by tf-wiki-discord** [comment]
More links for later:
Twitter's node API: https://www.npmjs.com/package/twitter
Python version of what we'd want: https://nickjanetakis.com/blog/use-twitters-api-and-a-few-command-line-tools-to-pick-a-random-reply

Twitter's own sample snippets: https://github.com/twitterdev/labs-sample-code

**Comment by tf-wiki-discord** [comment]
This should happen after the Promise refactor so that Rad can dispatch many tasks without creating infinite nested callbacks
